### ISSUE TITLE
What about light-weight processors  (e.g. using Common Expression Language)

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#10]

**Comment by Akaame** [comment]
The link to specification is broken.

Could you please elaborate on the "Acceptance Criteria" for this ticket?

Given the documentation on [Processors](https://github.com/argoproj-labs/argo-dataflow/blob/782c39a2b9224c67a3b76199d9aaf2c93f0e4aee/docs/PROCESSORS.md) what makes a processor "light-weight"? 

Cheers.
