### ISSUE TITLE
STAN does not appear to scale as expected

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#119]
@whynowy 

There's a file named `test-results.json` that I use to save test results into.

I've run `TestStanSourceStress` and its twin `TestStanSinkStress` with 1 replica and 2 replicas. Unlike Kafka, it does not scale as I would expect, ideally 2 replicas process 2x the messages of 1 replica, 3 replicas 3x etc. 

For STAN it seems more like 1.3x or 1.5x?

```
  "TestStanSinkStress/replicas=1.tps": 300,
  "TestStanSinkStress/replicas=2.tps": 350,
  "TestStanSourceStress/replicas=1.tps": 550,
  "TestStanSourceStress/replicas=2.tps": 700
```

This could be for a few reasons:

* My test run was bad.
* Test infra cannot support this load.
* Docker for Desktop cannot support the load.
* Bug?
* Configuration?

Could I please ask you to investigate?

**Comment by whynowy** [comment]
TPS calculation bug, after fixing:

```
  "TestStanSinkStress/replicas=1.tps": 100,
  "TestStanSinkStress/replicas=2.tps": 200,
  "TestStanSinkStress/replicas=3.tps": 300,
  "TestStanSinkStress/replicas=4.tps": 300,
  "TestStanSinkStress/replicas=5.tps": 350,
  "TestStanSourceStress/replicas=1.tps": 550,
  "TestStanSourceStress/replicas=2.tps": 700,
  "TestStanSourceStress/replicas=3.tps": 750,
  "TestStanSourceStress/replicas=4.tps": 750,
  "TestStanSourceStress/replicas=5.tps": 750,
```

**Comment by whynowy** [comment]
For source (read), single client achieves very high throughput, double clients do not get double performance, and it maintains at certain level even more clients are used.

For sink (write), it does gain double/triple performance when using more replicas at the beginning, which is expected. But continue adding more does not have a good result, possible reason:  my laptop limitation caused the steps pods or the STAN pod didn't get very good performance.
