### ISSUE TITLE
`stan: connection closed` error

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#120]
I'm seeing this error. I'm not sure if it is occurring during graceful shutdown.

**Comment by whynowy** [comment]
From splunk, all the logs related to `stan: connection closed` point to `\"time\":\"2021-07-14T18:04:35Z\"`, which was the time that I implemented [stan reliable reconnection](https://github.com/argoproj-labs/argo-dataflow/pull/112), and deployed to the cluster. After deployment, I manually killed stan pods for testing, I believe that is the reason the error was seen.


https://pi.nonprod.splunk.intuit.com/en-US/app/search/search?q=search%20clustername%3A%3Atech-pi-ppd-usw2-k8s%20%20index%3Diks%20sourcetype%3Dfluent%20%20%22stan%3A%20connection%20closed%22%20%22kubernetes.pod_name%22%3D%22test-encryption-encrypt-0%22&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-30d%40d&latest=now&display.general.type=events&display.prefs.events.count=50&sid=1628124980.16764_24CA7F83-6CCF-483A-9D76-4078CCA3BF69
