### ISSUE TITLE
Test with large messages (>1Mb)

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#177]
| Source | |
|---|---|
| HTTP | | 
| Kafka | | 
| STAN | |

| Sink | |
|---|---|
| HTTP | | 
| Kafka | | 
| STAN | |

**Comment by alexec** [comment]
Running 1Mb messages locally caused Docker for Desktop to crash. 100Kb is ok.

**Comment by sarabala1979** [comment]
| Source | 1 Mb|1.5 Mb|2 Mb|2.5 Mb|3 Mb|3.5 Mb|5 Mb|10 Mb|50 Mb|100 Mb|
|---|---|---|---|---|---|---|---|---|---|---|
| HTTP |TPS 1181 |TPS 1126|TPS 1122|TPS 1136| TPS 1137|TPS 1126| TPS 1139| TPS 1182| TPS 1182|TPS
| Kafka | | 
| STAN | |

| Source | 1 Mb|1.5 Mb|2 Mb|2.5 Mb|3 Mb|3.5 Mb|5 Mb|10Mb|50 Mb|100 Mb|
|---|---|---|---|---|---|---|---|---|---|---|
| HTTP |TPS 775 |TPS 783|TPS 782|TPS 795| TPS 795|TPS 783| TPS 769|TPS 750|TPS 769|TPS 783|
| Kafka | | 
| STAN | |

**Comment by sarabala1979** [comment]
@alexec Do you have any other datapoints?

**Comment by alexec** [comment]
I'm not sure about these numbers. I would expect TPS to become smaller and message size grows. But that does not appear to be the case?

**Comment by sarabala1979** [comment]
@alexec Something I discussed with Derek. I am checking message size kafka and STAN.  I am checking
