### ISSUE TITLE
NodeJS runtime

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#191]
We have an example of running using NodeJS, but we don't have a runtime for this, like we do for Python, Golang and Java. 

While this is not mandatory, it might be useful. I can see NodeJS being easy to write, and the runtimes provide good examples of how to write a main container.

**Comment by alexec** [comment]
@domderen FYI

**Comment by domderen** [comment]
Yup, once I get the SDK working, I can add a runtime for NodeJS as well.
