### ISSUE TITLE
Consumer group names that are just hex - confusing

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#219]
We should prefix the consumer group (or durable name) names with a helpful prefix, e.g.

`dataflow-${pipelineName}-`

**Comment by pradeepnnv** [comment]
Can I work on this?

**Comment by alexec** [comment]
Please!

**Comment by alexec** [comment]
I actually suggest a new format for the name.

`dataflow-${cluterName[0:3]}-${namespace[0:3]}-${pipeline[0:3]}-s-${source[0:3]}-${hash}`

In needs to be:

1. < 255 characters long (Kafka limitation)
2. globally unique
3. easier than hex for a human to at least guess which pipeline it might be
