### ISSUE TITLE
Update SDKs to support Generator Steps

### ISSUE THREAD

**Issue by domderen** [argoproj-labs/argo-dataflow#229]
At the moment all SDKs support image contract in terms of signaling when a step is ready to process messages, and accepting incoming messages from a source. It would be great if the SDKs would help build generator step, where a "handler" function would not accept any input, and could return multiple values over time. 

Unless you have some objections to extending SDKs that way I was thinking about working on it.

**Comment by alexec** [comment]
I think this is a great idea.
