### ISSUE TITLE
Document differences between source/sink types

### ISSUE THREAD

**Issue by domderen** [argoproj-labs/argo-dataflow#230]
I saw some documentation about limitations of certain sink/source types, but I'm not sure about general differences between those types, other than the size of the message and throughput. 

In particular I'm interested in the HTTP sink/source. Based on the information in limits, it seems that the HTTP type can handle very large message sizes, and can handle thousands of messages per second. If that is the case, I'm wondering why would I ever want to use a Kafka sink/source between my steps, if it can handle a similar throughput, but only much smaller message sizes. I'm wondering if HTTP sink/source might have problems with storing messages between steps, if the next step is not yet ready to consume it? Or is it less reliable, and might cause issues with message delivery? Or does the HTTP type has worse scalability, and might not be able to handle hundreds or thousands of steps using it as a message bus?

Similarly with nats, I'm wondering what are pros & cons as well as what usecases it might be good/bad for.

**Comment by alexec** [comment]
HTTP is stateless, so you would probably not want to connect steps using it, because it requires the first step that received the message to wait for all other steps to complete. 

This should be documented.
