### ISSUE TITLE
Improve ratio based scaling

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#242]
Currently we check to see if we need to scale based on pending messages by dividing the number of pending messages by a ratio to get the number of replicas.

This cause a lot of scaling saw, because adding another replica manages to pay down pending messages, until a scale-down occurs, and then we need to scale-up:

![image](https://user-images.githubusercontent.com/1142830/129272383-39a052d7-b164-475a-808c-227a547b237b.png)

See #243 #244

**Comment by edlee2121** [comment]
Perhaps just wait a little bit before scaling back down after a scale up or visa versa?

**Comment by alexec** [comment]
I did wonder if we should use round ratios down when scaling up and round up when scaling down.
