### ISSUE TITLE
Rate-based scaling

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#243]
Pending scaling seems like a great idea, but would rate-based scaling be better?

1. Users can and will need to estimate the TPS a single replica can cope with.
2. We can determine if we're processing less or at that than that rate. 
3. If we're processing less, we can probably scale-down.
4. If we're processing at that, rate then we might need to scale-up.

**Comment by edlee2121** [comment]
Perhaps more like, create enough replicas to drain the pending queue in x seconds where x is big enough to justify spinning up a new pod
