### ISSUE TITLE
Multi-cluster

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#288]
For Argo Workflows, we're building a multi-cluster solution. I wonder if this is something we want for dataflow? It's easier to do today, than tomorrow, but is not without cost. I'm not clear about the benefit either.

**Comment by edlee2121** [comment]
I'm thinking we should focus on single cluster for now.

**Comment by alexec** [comment]
I'm not actually sure users would want it. Just collecting 👍
