### ISSUE TITLE
tech debt: better sidecar lifecycle

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#422]
The global context we use within the sidecar/runner is registered with SIGTERM.

It makes it hard to carefully shutdown the sidecar in order, because components might get the context cancelled too soon. This code will be buggy, and we do not want bugs at all. 

We need a better way to do this, some way to enable graceful ordered shutdown.

Could a DI library help?

@whynowy @alexmt @jessesuen any suggestions

**Comment by jessesuen** [comment]
I think I'm missing a lot of context but I have some questions:
1. who controls the entry point? dataflow or users?
2. How is the initial SIGTERM sent? If via `kubectl delete` then this signal is spammed to all containers simultaneously, and then all handling/coordination would have to happen by the entrypoint script/binary, and we may not have control depending on the answer to question 1

If we have control over entrypoint AND we can control the SIGTERM ordering, then I believe you have already solved this using touchfiles with the Argo Workflow containerset feature.

**Comment by alexec** [comment]
I think my question is more generally about Golang apps rather than Kubernetes especially. How would you control the order of shutdown of an app, and be able to say component A starts before component B, but is cleaned up in the reverse order?

**Comment by jessesuen** [comment]
If this is a purely go / goroutine problem, I would solve this by pushing the stop channels of each component onto a stack, as well as an optional cleanup callback function if desired. Then when a SIGTERM is received, close the stop channels in LIFO order, calling the cleanup callbacks as well.

Also, if this is all happening in one method, you could leverage the LIFO behavior of defer()
