### ISSUE TITLE
Quickstart does not seem to work with examples

### ISSUE THREAD

**Issue by Rob-Fletcher** [argoproj-labs/argo-dataflow#448]
I am trying to play around with dataflow to understand it a bit better but the quick start deployment doesnt seem to work correctly. The input pod that is created which seems like its supposed to be pushing messages to kafka fails. It looks like some other pod is missing. The input pod is using curl to hit a testapi, but there isnt anything like that deployed in any of the quick start instructions or manifests. Am I missing something or is there more to the setup that is missing from the instructions?

**Comment by Rob-Fletcher** [comment]
I was just trying to write some messages to it using the kafka-console-producer.sh and port forwarding the svc/kafka-broker but running into some errors. I dont have a ton of experience with kafka so Im not sure if the configuration is just not setup to be able to do that.

```
[2021-10-08 12:24:39,481] WARN [AdminClient clientId=adminclient-1] Error connecting to node kafka-broker:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: kafka-broker
```

**Comment by alexec** [comment]
cat you add `127.0.0.1 kafka-broker` to your /etc/hosts?
