### ISSUE TITLE
Investigate Redis Streams

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#484]
I want to get understanding of the usual things:

https://github.com/argoproj-labs/argo-dataflow/issues/321

**Comment by whynowy** [comment]
Basic
Written in C language
No wildcard stream support
No partition
Structured data - Map
ID: timestamp-seq - 1518951480106-0
Query by range - start ID / end ID
Explicit acknowledgment per message
Ability to inspect the pending items
Ability to see its private past history of messages
Ability to remove single messages from stream
Dead letter
At-Least-Once
Sync write only?

Consumer Group
Different implementation from Kafka
Needs to be created explicitly
Give a consumer name to subscribe with consumer group
Need manual operation to recover from permanent consumer failures

Persistence
RDB - snapshot in DB
AOF - append only file

Latency
Processed between 0 and 1 ms -> 74.11%
Processed between 1 and 2 ms -> 25.80%
Processed between 2 and 3 ms -> 0.06%
Processed between 3 and 4 ms -> 0.01%
Processed between 4 and 5 ms -> 0.02%
