### ISSUE TITLE
Ability to specify envs for code step

### ISSUE THREAD

**Issue by zewelor** [argoproj-labs/argo-dataflow#517]
It would be helpful to have option to pass env when using code step

**Comment by alexec** [comment]
The code could be added here:

https://github.com/argoproj-labs/argo-dataflow/blob/7fe4585ae01a900c36114848dce932b5863263ab/api/v1alpha1/code.go#L9

Either similar to `Container`:

https://github.com/argoproj-labs/argo-dataflow/blob/7fe4585ae01a900c36114848dce932b5863263ab/api/v1alpha1/container.go#L11

Or maybe `Code` should sub-class `Container` and get all the fields for free?

Would you like to submit a PR?

**Comment by zewelor** [comment]
Thats for reply. So from what I can see. I could use container step, as code step uses container step ? As for PR maybe I could try, I have no go coding experience. So not sure how to setup everything to code and test it ?

**Comment by alexec** [comment]
There is a contributing guide:

https://github.com/argoproj-labs/argo-dataflow/blob/main/docs/CONTRIBUTING.md

Golang maybe the easier language ever invented, I recommend doing the Tour of Go:

https://go.dev/tour/welcome/1
