### ISSUE TITLE
Maybe remove FIFO

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#518]
Rationale:

* Not sure it will be used much
* Does not support new lines in messages
* Does not support meta-data 
* Does not vertically scale (unlike HTTP)

**Comment by aiicore** [comment]
@alexec In case of pipeline with argo steps, does the FIFOs would make less performance impact? Having no additional http server for handling messages inside docker image used as steps could be a benefit on smaller platforms, I think.
btw. Do I understand correctly, that opening 'in' and 'out' FIFOs, satisfies container image contract in matter of readiness?

**Comment by alexec** [comment]
I don't expect FIFO will be faster, or slower. It just not as good as the other option.
