### ISSUE TITLE
ArgoLabs Dataflow is on hold - use Numaflow

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#529]
~We've put Dataflow on hold as we are planning on some significant changes and redesign. Stay tuned.~

**Comment by Bouwdie** [comment]
@alexec we would love to start testing dataflow, do you maybe have some insights in what the changes will be? and how fundamental :dancers:

**Comment by alexec** [comment]
We're currently working a new version:

* It's focussed on providing ways to do windowing operations. This is something difficult for the old version.
* It's currently supports Kafka, does not provide support for the variety of source and sinks.
* It has many similar concepts and ideas as this version (e.g. pipelines are CRDs).
* It should be an easy migration from the older version to this version.
* It should be available in about 3mo.

With that in mind, any testing you do with old dataflow, will be extremely instructive and helpful.

**Comment by cdeboeser** [comment]
Already excited to see this unfold! Are you looking for contributors?

Also another question: Is there any aspiration to allow for batch jobs, ie reading a bounded source including fan-out and -in? Use case is finite data processing jobs, along ETL lines really.

**Comment by ant31** [comment]
Hello, 
Why is it not built in the opensource, isn't argo a CNCF project?

**Comment by BenCoughlan15** [comment]
Hey, is this still in the works? I'm wondering if Nats streaming will still be supported?

**Comment by openrory** [comment]
Hey guys, any update on the re-launch date yet?

**Comment by louisnow** [comment]
Argo 3.4 rc1 has removed dataflow pipelines from the UI 

https://github.com/argoproj/argo-workflows/issues/8998

**Comment by alexec** [comment]
@edlee2121 can I please ask you to comment on this issue to give users insight into the future.

**Comment by edlee2121** [comment]
Hi all, dataflow is being reworked as part of a new project focused on operational analytics.
Please check it out.
https://github.com/numaproj/numaflow

**Comment by vigith** [comment]
Now that we have open-sourced numaflow - https://github.com/numaproj/numaflow, shall we close this issue?
