### ISSUE TITLE
Cluster variable

### ISSUE THREAD

**Issue by IvanKolbasiuk** [argoproj-labs/argo-dataflow#534]
Could you explain the format for 
`Cluster:             os.Getenv(dfv1.EnvCluster)`
in the controller manager code
I've got this error during setup on Azure AKS

> `kubectl logs -f controller-manager-f66bd546d-w2l9f -n dev manager
> time="2022-02-02T22:42:50Z" level=info msg=cpu numCPU=2
> time="2022-02-02T22:42:50Z" level=info msg=process pid=1
> time="2022-02-02T22:42:50Z" level=info msg=version version=v0.0.0-latest-0
> time="2022-02-02T22:42:50Z" level=info msg="scaling config" defaultPeekDelay=4m0s defaultScalingDelay=1m0s
> time="2022-02-02T22:42:50Z" level=info msg="reconciler config" imageFormat="quay.io/argoprojlabs/%s:latest" imagePullSecrets="[]" pullPolicy="\"\"" runnerImage="quay.io/argoprojlabs/dataflow-runner:latest" updateInterval=15s
> I0202 22:42:51.603095       1 request.go:655] Throttling request took 1.000760856s, request: GET:https://10.0.0.1:443/apis/coordination.k8s.io/v1?timeout=32s
> time="2022-02-02T22:42:52Z" level=info msg="metrics server is starting to listen" addr="127.0.0.1:9090" logger=controller-runtime.metrics
> panic: unable to create controller manager: cluster must be set
> 
> goroutine 1 [running]:
> main.main()
> 	/workspace/manager/main.go:97 +0xa4e`

Thanks

**Comment by alexec** [comment]
All clusters you install must be given a unique name. This is sometimes used to create UUIDs for messages.

**Comment by IvanKolbasiuk** [comment]
Thanks @alexec , I tried with setting env variable for deployment, but still receive the same error.
`- args:
        - --metrics-addr=127.0.0.1:9090
        - --enable-leader-election
        command:
        - /manager
        image: quay.io/argoprojlabs/dataflow-controller:latest
        name: manager
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        env:
        - name: Cluster
          value: "cluster name"
`

**Comment by IvanKolbasiuk** [comment]
Found quick_start.yaml in the release. Fixed with env: ARGO_DATAFLOW_CLUSTER:
