### ISSUE TITLE
Add trace IDs for debugging

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#65]
We should use industry-standard, e.g. OpenTelemery (was Open Zipkin).

**Comment by alexec** [comment]
https://github.com/nats-io/not.go

**Comment by alexec** [comment]
https://medium.com/data-rocks/kafka-record-tracing-379ed2b0af51

**Comment by whynowy** [comment]
Opentelemetry already has first class support for Kafka, but nats is not there. `not.go` is still for opentracing, not opentelemetry.

**Comment by alexec** [comment]
Superseded by #161
