### ISSUE TITLE
Question: Dataflow sidecar future capabilities

### ISSUE THREAD

**Issue by ddseapy** [argoproj-labs/argo-dataflow#73]
What capabilities do you expect the dataflow sidecar to provide in the future?  For instance while clearly different from dapr in many regards, do you expect any of argo dataflow's capabilities to eventually overlap with those that something like a Dapr sidecar provides?

Thanks!

**Comment by alexec** [comment]
https://dapr.io/

Dataflow is not aimed at building micro-services or applications like Dapr. I don't expect users to use it to serve HTTP requests for example.

**Comment by ddseapy** [comment]
thanks!
